##########################################################################
#                                                                        #
#                          Service COnfig Part                           #
#                                                                        #
##########################################################################

postgres:
  username: "admin"
  password: "password"
  host: "postgres:5432"
  schema: "micro"
